{
  imports = [
    ./apps
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./compilers.nix
    ./docker.nix
    ./env.nix
    ./home-manager.nix
    ./hyprland.nix
    ./kernel.nix
    ./mime.nix
    ./network.nix
    ./nh.nix
    ./nix-ld.nix
    ./nix.nix
    ./postgres.nix
    ./timezone.nix
    ./udev-rules.nix
    ./udisks2.nix
    ./user.nix
    ./zram.nix
  ];
}
